### ISSUE TITLE
Getting "flutter: error!!!!"

### ISSUE THREAD

**Issue by j2brian703** [Shark01/google_map_polyline#1]
I get "flutter: error!!!!" every time I call "_getPolylinesWithLocation" or "_getPolylinesWithAddress". The error message I get is not very descriptive and not sure which part I did wrong.

**Comment by shakirsamoon** [comment]
> I get "flutter: error!!!!" every time I call "_getPolylinesWithLocation" or "_getPolylinesWithAddress". The error message I get is not very descriptive and not sure which part I did wrong.

Sorry for the delayed reply.
Do you still have the error?

If yes, please feel free to attach your code.

**Comment by j2brian703** [comment]
Yes I'm still getting the same error. Actually I downloaded your example and replaced API Key in the main.dart with my Directions API key and I get the same error.

**Comment by shakirsamoon** [comment]
> Yes I'm still getting the same error. Actually I downloaded your example and replaced API Key in the main.dart with my Directions API key and I get the same error.

I cloned the repo and test it out the example project. There is no error.
I'm not sure what error you got.

Can you copy paste your debug console log?
I think it should help me to look more in to this matter.

And also my suggestions for you to check.
- Check your API key. Sometimes you haven't enable the API key correctly. It should enabled,
  - **Directions API** ( To load polyline data )
  - **Maps SDK for Android** ( To show map in Android )
  - **Maps SDK for iOS** ( To show map in iOS )

- Did you applied your keys right? Key should add to, 
  - **AndroidManifest.xml** ( Android folder - _"\android\app\src\main\AndroidManifest.xml"_ )
  - **AppDelegate.m** ( iOS folder - _"\ios\Runner\AppDelegate.m"_ )
  - **main.dart** ( lib folder )

**Comment by j2brian703** [comment]
I figured it out. You have to enable Billing from Google Cloud Console. But I think your package does not help my project although you did a great job. Thanks.
