### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null. E/flutter ( 4735): Receiver: null

### ISSUE THREAD

**Issue by gadishimwe** [Shark01/google_map_polyline#10]
Hi @Shark01. I'm getting this error every time I try to pass polylines from either googleMapPolyline.getCoordinatesWithLocation() or googleMapPolyline.getPolylineCoordinatesWithAddress() to GoogleMap widget. And above all, I'm getting null from googleMapPolyline.getCoordinatesWithLocation() which refers to this same issue #2.

Any help would be much appreciated. Thanks

This is my flutter doctor by the way,

Gads-MBP:~ gad$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-RW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!
Gads-MBP:~ gad$

**Comment by gadishimwe** [comment]
Fixed the issue. It was my code, I wasn’t waiting to get the coordinates first before pass it to GoogleMap()

> Hi @Shark01. I'm getting this error every time I try to pass polylines from either googleMapPolyline.getCoordinatesWithLocation() or googleMapPolyline.getPolylineCoordinatesWithAddress() to GoogleMap widget. And above all, I'm getting null from googleMapPolyline.getCoordinatesWithLocation() which refers to this same issue #2.
> 
> Any help would be much appreciated. Thanks
> 
> This is my flutter doctor by the way,
> 
> Gads-MBP:~ gad$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-RW)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
> [✓] Android Studio (version 4.0)
> [✓] VS Code (version 1.46.1)
> [✓] Connected device (1 available)
> 
> • No issues found!
> Gads-MBP:~ gad$

**Comment by shakirsamoon** [comment]
Hello @gadishimwe 
I'm glad that you fixed your issue by yourself.
And I want you to inform that I have discontinued maintaining this package. So use it at your own risk.
If you need to add features, please feel free to fork the repository and use it.

**Comment by gadishimwe** [comment]
No problem. Thanks for the response.
